### ISSUE TITLE
instrcutions tests

### ISSUE THREAD

**Issue by xor2003** [frranck/asm2c#4]
I'm developing similar project using Python (masm2c) because I don't know Swift.
I have ported i386 instructions tests from qemu.
You can reuse it too:
[_qemu_tests.zip](https://github.com/frranck/asm2c/files/4732844/_qemu_tests.zip)
It can be run directly on hardware or translated using masm2c. So you can compare output of instructions (regs and flags) and make sure all instructions calculate well as hardware.

**Comment by frranck** [comment]
thanks but I don't maintain this really, this was made for mrboom's port.
